# File: compose.override.yaml
# Author: Milan Vodák <xvodak07@stud.fit.vut.cz>
# Description: Development overrides for the containerized environment.

services:
  frontend:
    build:
      target: dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/code
      - /code/node_modules

  backend:
    build:
      target: dev
    ports:
      - "3001:8000"
    volumes:
      - ./backend/app:/code/app
      - ./backend/diff_c:/code/diff_c

  neo4j:
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
